apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-with-configmap-env-valuesfrom
data:
  ip: "10.0.0.1"
  server: "web"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap-env-valuesfrom
spec:
  containers:
  - image: nginx
    name: pod-with-configmap
    envFrom:
      - configMapRef:
          name: pod-with-configmap-env-valuesfrom
