apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: runtimeclass-teste
  name: runtimeclass-teste
spec:
  runtimeClassName: "runsc"
  containers:
    - image: nginx
      name: runtimeclass-teste
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
