apiVersion: v1
kind: Pod
metadata:
  name: service-test-loadbalancer
  labels:
    type: webapp
    svcType: loadbalancer
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-test-loadbalancer
spec:
  type: LoadBalancer
  selector:
    type: webapp
    svcType: loadbalancer
  ports:
    - name: name
      port: 8080 # Porta que o serviço exportará para escuta
      targetPort: 80 # Porta do container
