apiVersion: v1
kind: Pod
metadata:
  name: service-test-nodeport
  labels:
    type: webapp
    svcType: NodePort
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: servicetest-nodeport
spec:
  type: NodePort
  selector:
    type: webapp
    svcType: NodePort
  ports:
    - name: name
      port: 8080 # Porta que o serviço exportará para escuta
      targetPort: 80 # Porta do container
      #nodePort: 31100 # Não é necessário preencher. O k8s preencherá automaticamente
