apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-with-imagepullsecrets
  name: deploy-with-imagepullsecrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-with-imagepullsecrets
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-with-imagepullsecrets
    spec:
      imagePullSecrets:
        - name: docker-credentials
      containers:
        - image: fabioluciano/docker-jnlp-slave-aws
          resources: {}
          name: teste
status: {}
