apiVersion: v1
kind: Secret
metadata:
  name: pod-with-secrets-env-value
data:
  username: YWRtaW4= 
  password: MTIzNDU=
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secrets-env-value
spec:
  containers:
  - image: nginx
    name: pod-with-secrets-envfrom
    env:
      - name: MEUUSUARIO
        valueFrom:
         secretKeyRef:
          name: pod-with-secrets-env-value
          key: username

