apiVersion: v1
kind: Secret
metadata:
  name: pod-with-secrets-envfrom
data:
  username: YWRtaW4= 
  password: MTIzNDU=
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secrets-envfrom
spec:
  containers:
  - image: nginx
    name: pod-with-secrets-envfrom
    envFrom:
      - secretRef:
          name: pod-with-secrets-envfrom 
status: {}
