apiVersion: v1                                         
kind: Secret
metadata:
  name: pod-with-secrets-volume-items
data:
  username: YWRtaW4= 
  password: MTIzNDU=
---
apiVersion: v1
kind: Pod 
metadata:
  name: pod-with-secrets-volume-items
spec:
  containers:
  - image: nginx
    name: pod-with-secrets-envfrom
    volumeMounts:
      - name: secret-data
        mountPath: /secret
  volumes:
    - name: secret-data
      secret:
        secretName: pod-with-secrets-volume-items
        items:
          - key: username
            path: USUARIO.txt
