apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rbac-cli-access-sa
  name: rbac-cli-access-sa
spec:
  serviceAccountName: list-pods
  containers:
    - args:
        - sh
        - -c
        - sleep infinity
      image: alpine
      name: rbac-cli-access-sa
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
