apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reader
  name: reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - command:
        - kubectl
        - get
        - pods;
        - sleep
        - "36000"
        image: bitnami/kubectl
        name: kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: reader-pods
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: reader-role-x-reader-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reader-pods
subjects:
- kind: ServiceAccount
  name: reader
