apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ex-14
  name: ex-14
spec:
  containers:
  - command:
    - busybox
    args:
    - sleep
    - "3600"
    image: busybox
    name: ex-14
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
