apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ex-secret-pod1
  name: ex-secret-pod1
spec:
  containers:
  - image: nginx
    name: ex-secret-pod1
    ports:
    - containerPort: 80
    resources: {}
    env:
    - name: SENHA
      valueFrom:
        secretKeyRef:
          name: user-secret-kubectl
          key: pass
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
