apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: seccomp-test
  name: seccomp-test
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profile/fine-grained.json
  containers:
    - image: hashicorp/http-echo:1.0
      name: seccomp-test
      resources: {}
      args:
        - "-text=Hello World"
      securityContext:
        allowPrivilegeEscalation: false
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
