apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-pod-test
spec:
  limits:
    - type: Pod
      min:
        cpu: 250m
        memory: 500M
      max:
        cpu: 500m
        memory: 1G
---
apiVersion: v1
kind: Pod
metadata:
  name: limitrange-pod-test
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: 250m
          memory: 500M
        limits:
          cpu: 250m
          memory: 800M
    - name: busybox
      image: busybox
      command:
        - "sleep"
        - "3600"
      resources:
        requests:
          cpu: 250m
          memory: 200M
        limits:
          cpu: 250m
          memory: 200M
