apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: teste
  name: teste
spec:
  containers:
  - image: nginx
    name: teste
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
