apiVersion: v1
kind: ResourceQuota
metadata: 
  name: resourcequota-test
spec:
  hard:
    cpu: 4
    memory: 8G
    pods: 2
    secrets: 1
---
apiVersion: v1
kind: Pod
metadata:
  name: resourcequota-teste-1
spec:
  containers:
  - image: nginx
    name: dddd
    resources:
      requests:
        cpu: 400m
        memory: 500M
---
apiVersion: v1
kind: Pod
metadata:
  name: resourcequota-teste-2
spec:
  containers:
  - image: nginx
    name: dddd
    resources:
      requests:
        cpu: 400m
        memory: 500M
