apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-with-serviceaccount-automount-false
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-serviceaccount-automount-false
spec:
  serviceAccountName: pod-with-serviceaccount-automount-false
  automountServiceAccountToken: false
  containers:
  - image: nginx
    name: pod-with-serviceaccount-automount-false
