apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: serviceaccount-with-token
---
apiVersion: v1
kind: Secret
metadata:
  name: serviceaccount-with-token
  annotations:
    kubernetes.io/service-account.name: serviceaccount-with-token
type: kubernetes.io/service-account-token
