apiVersion: v1
kind: Pod
metadata:
  name: pod-with-emptydir-volume
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: empty
        mountPath: /usr/share/nginx/html
  - image: busybox
    name: html-writter
    volumeMounts:
      - name: empty
        mountPath: /html
    command: ["sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done;
  volumes:
    - name: empty
      emptyDir: {}
