apiVersion: v1
kind: PersistentVolume
metadata:
  name: pod-with-pvc
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi    
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pod-with-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: pvc-data
        mountPath: /app
  volumes:
    - name: pvc-data
      persistentVolumeClaim:
        claimName: pod-with-pvc
