apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: teste
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: claim-data
  volumes:
    - name: claim-data
      persistentVolumeClaim:
        claimName: myclaim
