name: Lint de Markdown

on:
  pull_request:
    paths:
      - "**/*.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Obter arquivos modificados
        id: changed-files
        run: |
          echo "files=$(git diff --name-only origin/${{ github.base_ref }}..HEAD | grep '\.md$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Executar markdownlint-cli2 nos arquivos modificados
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          command: "${{ steps.changed-files.outputs.files }} '#node_modules'"
          config: ".markdownlint.json"
