name: Lint de Markdown

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Obter arquivos modificados
        id: changed-files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' | tr '\n' ' ')"

      - name: Executar markdownlint-cli2 nos arquivos modificados
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: '**/*.md'
          config: '.markdownlint.json'
