name: Lint de Markdown

on:
  pull_request:
    paths:
      - "**/*.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            src/**/*.md
          separator: ","

      - name: Executar markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v19
        if: steps.changed-files.outputs.all_changed_files != ''
        with:
          globs: "${{ steps.changed-files.outputs.all_changed_files }}"
          config: ".markdownlint.json"
          separator: ","
