name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Define required permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment happens at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Install mdBook plugins
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook-admonish mdbook-plantuml mdbook-alerts

      - name: Setup mdBook Admonish plugin
        run: mdbook-admonish install

      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "latest"

      - name: Install PlantUML dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y plantuml

      - name: Build mdBook documentation
        run: mdbook build

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "book"

      - name: Deploy to GitHub Pages
        if: ${{ env.ACT != 'true' }}
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Local deployment simulation
        if: ${{ env.ACT == 'true' }}
        run: |
          echo "Simulando deploy local..."
          mkdir -p /tmp/deploy-preview
          cp -r book/* /tmp/deploy-preview/
          echo "Conteúdo copiado para /tmp/deploy-preview"
