name: Verificação Ortográfica

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y aspell aspell-pt aspell-pt-br

      - name: Verificar dicionários disponíveis
        run: aspell dicts

      - name: Verificar se aspell reconhece pt_BR
        run: aspell --lang=pt_BR dump dicts


      - name: Setar localidade
        run: |
          export LANG=pt_BR.UTF-8
          export LC_ALL=pt_BR.UTF-8


      - name: Executar verificação ortográfica
        uses: rojopolis/spellcheck-github-actions@0.47.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown