name: Verificação Ortográfica

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install --save-dev @cspell/dict-pt-br

      - name: Executar verificação ortográfica
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: './cspell.json'
          files: |
            **/*.md
          inline: error
          strict: true
          suggestions: true