name: Verificação Ortográfica

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y aspell aspell-pt-br

      - name: Executar verificação ortográfica
        uses: rojopolis/spellcheck-github-actions@0.23.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown